# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Crypto Antelope
#email: ""
description: >- # this means to ignore newlines until "baseurl:"
  Compartiendo los mejores sitios, tips y comparativas de sitios en los que se puedan ocupar criptomendas.
  Así como exchanges, casinos, comercios, etc.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: cryptoAntelope
github_username:  cryptoantelope
#youtube_username: 


social_links:
    twitter: cryptoAntelope
    github:  cryptoAntelope
    youtube_channel: UCQUjBPiXbSjr_3inCGQox-g
    youtube_channel_name: Crypto Antelope

# Build settings
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - casinos.md
  - exchanges.md
  - about.md

google_analytics: UA-151767620-1

disqus:
  shortname: cryptoantelope
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
